name: blender-render

# Only run this when the master branch changes
on:
  push:
    branches:
    - master

# This job installs dependencies and render the animation
jobs:
  blender-render:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install dependencies
      run: sudo apt-get install blender
    # Render the animation
    - name: Render the animation
      run: |
        blender -b welcome.blend -a
